### ISSUE TITLE
It throws an exception. 

### ISSUE THREAD

**Issue by sidd4698** [ShikhaSoni/AndroidSimpledb#1]
11-16 19:01:49.492    2144-2144/com.simpledb.info W/System.err﹕ java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.CharSequence android.widget.TextView.getText()' on a null object reference
11-16 19:01:49.492    2144-2144/com.simpledb.info W/System.err﹕ at com.simpledb.info.MainActivity$1.onClick(MainActivity.java:41)
11-16 19:01:49.492    2144-2144/com.simpledb.info W/System.err﹕ at android.view.View.performClick(View.java:5198)
11-16 19:01:49.492    2144-2144/com.simpledb.info W/System.err﹕ at android.view.View$PerformClick.run(View.java:21147)
11-16 19:01:49.492    2144-2144/com.simpledb.info W/System.err﹕ at android.os.Handler.handleCallback(Handler.java:739)
11-16 19:01:49.492    2144-2144/com.simpledb.info W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:95)
11-16 19:01:49.492    2144-2144/com.simpledb.info W/System.err﹕ at android.os.Looper.loop(Looper.java:148)
11-16 19:01:49.492    2144-2144/com.simpledb.info W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5417)
11-16 19:01:49.492    2144-2144/com.simpledb.info W/System.err﹕ at java.lang.reflect.Method.invoke(Native Method)
11-16 19:01:49.492    2144-2144/com.simpledb.info W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-16 19:01:49.492    2144-2144/com.simpledb.info W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-16 19:01:49.639    2144-2167/com.simpledb.info W/EGL_emulation﹕ eglSurfaceAttrib not implemented
11-16 19:01:49.639    2144-2167/com.simpledb.info W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xad739380, error=EGL_SUCCESS
11-16 19:01:49.997    2144-2167/com.simpledb.info E/Surface﹕ getSlotFromBufferLocked: unknown buffer: 0xab7959c0
11-16 19:02:19.116    2144-2167/com.simpledb.info W/EGL_emulation﹕ eglSurfaceAttrib not implemented
11-16 19:02:19.116    2144-2167/com.simpledb.info W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xad739a60, error=EGL_SUCCESS
11-16 19:02:19.772    2144-2167/com.simpledb.info E/Surface﹕ getSlotFromBufferLocked: unknown buffer: 0xab796d00
11-16 19:02:27.322    2144-2167/com.simpledb.info E/Surface﹕ getSlotFromBufferLocked: unknown buffer: 0xab7959c0

**Comment by sidd4698** [comment]
@ShikhaSoni please investigate
